# Generated by Django 5.1.2 on 2024-10-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('Enviado', 'Enviado'), ('En Proceso', 'En Proceso'), ('Entrevista', 'Entrevista'), ('Ofrecido', 'Ofrecido'), ('Rechazado', 'Rechazado')], max_length=50)),
                ('responsibilities', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('salary_benefits', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
