# Generated by Django 5.1.2 on 2024-10-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='responsibilities',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('En Proceso', 'En Proceso'), ('Entrevistas', 'Entrevistas'), ('Ofrecido', 'Ofrecido'), ('Rechazado', 'Rechazado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='technologies',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Javascript', 'Javascript')], max_length=100),
        ),
    ]
